#The duration of the period where you can give a review after the a contract ended.
review-period: 5



#The number of characters and lines the player can give in a comment.
max-comment-lines: 4
max-comment-char-per-line: 20